/*----------
Q2. Revenue by Category
Calculate total revenue generated by each product category.
Inlcude the percentage contribution of each category to total revenue.
----------*/
SELECT
    p.category_id,
    c.category_name,
    ROUND(SUM(oi.total_sale)) AS total_sale,
    ROUND((SUM(oi.total_sale::NUMERIC) * 100 -- NUMERIC to get decimals
        / (SELECT SUM(total_sale::NUMERIC) FROM order_items)), 2) percentage_contribution
FROM order_items oi
JOIN products p ON p.product_id = oi.product_id
LEFT JOIN category c ON c.category_id = p.category_id
GROUP BY 1, 2
ORDER BY 3 DESC;